//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace ZenChat.ZenChatService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ZenChatService.ServiceClasses")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NameField;
        
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatRoom", Namespace="http://schemas.datacontract.org/2004/07/ZenChatService.ServiceClasses")]
    public partial class ChatRoom : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZenChat.ZenChatService.User AdminField;
        
        private bool CanWriteMessagesField;
        
        private System.DateTime CreatedField;
        
        private int IdField;
        
        private System.Collections.Generic.List<ZenChat.ZenChatService.User> MembersField;
        
        private System.Collections.Generic.List<ZenChat.ZenChatService.ChatMessage> MessagesField;
        
        private string TopicField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZenChat.ZenChatService.User Admin {
            get {
                return this.AdminField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminField, value) != true)) {
                    this.AdminField = value;
                    this.RaisePropertyChanged("Admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanWriteMessages {
            get {
                return this.CanWriteMessagesField;
            }
            set {
                if ((this.CanWriteMessagesField.Equals(value) != true)) {
                    this.CanWriteMessagesField = value;
                    this.RaisePropertyChanged("CanWriteMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ZenChat.ZenChatService.User> Members {
            get {
                return this.MembersField;
            }
            set {
                if ((object.ReferenceEquals(this.MembersField, value) != true)) {
                    this.MembersField = value;
                    this.RaisePropertyChanged("Members");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ZenChat.ZenChatService.ChatMessage> Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Topic {
            get {
                return this.TopicField;
            }
            set {
                if ((object.ReferenceEquals(this.TopicField, value) != true)) {
                    this.TopicField = value;
                    this.RaisePropertyChanged("Topic");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMessage", Namespace="http://schemas.datacontract.org/2004/07/ZenChatService.ServiceClasses")]
    public partial class ChatMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.List<ZenChat.ZenChatService.User> ArrivedAtField;
        
        private ZenChat.ZenChatService.User AuthorField;
        
        private System.DateTime CreatedField;
        
        private int IdField;
        
        private string MessageField;
        
        private System.Collections.Generic.List<ZenChat.ZenChatService.User> ReadByField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ZenChat.ZenChatService.User> ArrivedAt {
            get {
                return this.ArrivedAtField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrivedAtField, value) != true)) {
                    this.ArrivedAtField = value;
                    this.RaisePropertyChanged("ArrivedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZenChat.ZenChatService.User Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ZenChat.ZenChatService.User> ReadBy {
            get {
                return this.ReadByField;
            }
            set {
                if ((object.ReferenceEquals(this.ReadByField, value) != true)) {
                    this.ReadByField = value;
                    this.RaisePropertyChanged("ReadBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrivateConversation", Namespace="http://schemas.datacontract.org/2004/07/ZenChatService.ServiceClasses")]
    public partial class PrivateConversation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.List<ZenChat.ZenChatService.User> MembersField;
        
        private System.Collections.Generic.List<ZenChat.ZenChatService.ChatMessage> MessagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ZenChat.ZenChatService.User> Members {
            get {
                return this.MembersField;
            }
            set {
                if ((object.ReferenceEquals(this.MembersField, value) != true)) {
                    this.MembersField = value;
                    this.RaisePropertyChanged("Members");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ZenChat.ZenChatService.ChatMessage> Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zenchatservice.azurewebsites.net/ZenChat.svc", ConfigurationName="ZenChatService.ZenChatService")]
    public interface ZenChatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/ChangeUsername" +
            "", ReplyAction="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/ChangeUsername" +
            "Response")]
        System.Threading.Tasks.Task<ZenChat.ZenChatService.User> ChangeUsernameAsync(int userId, string newUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/GetUser", ReplyAction="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/GetUserRespons" +
            "e")]
        System.Threading.Tasks.Task<ZenChat.ZenChatService.User> GetUserAsync(string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/GetUserFromId", ReplyAction="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/GetUserFromIdR" +
            "esponse")]
        System.Threading.Tasks.Task<ZenChat.ZenChatService.User> GetUserFromIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/Login", ReplyAction="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/LoginResponse")]
        System.Threading.Tasks.Task<System.Tuple<int, ZenChat.ZenChatService.User>> LoginAsync(string phone, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/GetFriends", ReplyAction="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/GetFriendsResp" +
            "onse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ZenChat.ZenChatService.User>> GetFriendsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/AddFriend", ReplyAction="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/AddFriendRespo" +
            "nse")]
        System.Threading.Tasks.Task AddFriendAsync(int userId, string otherPhone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/RemoveFriend", ReplyAction="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/RemoveFriendRe" +
            "sponse")]
        System.Threading.Tasks.Task RemoveFriendAsync(int userId, string otherPhone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/GetAllChatRoom" +
            "s", ReplyAction="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/GetAllChatRoom" +
            "sResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ZenChat.ZenChatService.ChatRoom>> GetAllChatRoomsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/GetChatRoom", ReplyAction="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/GetChatRoomRes" +
            "ponse")]
        System.Threading.Tasks.Task<ZenChat.ZenChatService.ChatRoom> GetChatRoomAsync(int chatRoomId, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/CreateChatRoom" +
            "", ReplyAction="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/CreateChatRoom" +
            "Response")]
        System.Threading.Tasks.Task<ZenChat.ZenChatService.ChatRoom> CreateChatRoomAsync(int userId, string topic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/InviteToChatRo" +
            "om", ReplyAction="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/InviteToChatRo" +
            "omResponse")]
        System.Threading.Tasks.Task InviteToChatRoomAsync(int userId, string phoneNumber, int chatRoomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/RemoveFromChat" +
            "Room", ReplyAction="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/RemoveFromChat" +
            "RoomResponse")]
        System.Threading.Tasks.Task RemoveFromChatRoomAsync(int userId, string phoneNumber, int chatRoomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/WriteGroupChat" +
            "Message", ReplyAction="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/WriteGroupChat" +
            "MessageResponse")]
        System.Threading.Tasks.Task<ZenChat.ZenChatService.ChatRoom> WriteGroupChatMessageAsync(int userId, int chatRoomId, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/GetPrivateConv" +
            "ersation", ReplyAction="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/GetPrivateConv" +
            "ersationResponse")]
        System.Threading.Tasks.Task<ZenChat.ZenChatService.PrivateConversation> GetPrivateConversationAsync(int userId, string otherPhone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/WritePrivateCh" +
            "atMessage", ReplyAction="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/WritePrivateCh" +
            "atMessageResponse")]
        System.Threading.Tasks.Task<ZenChat.ZenChatService.PrivateConversation> WritePrivateChatMessageAsync(int userId, string otherPhone, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/ReadChatMessag" +
            "e", ReplyAction="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/ReadChatMessag" +
            "eResponse")]
        System.Threading.Tasks.Task ReadChatMessageAsync(int userId, int messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/RecieveChatMes" +
            "sage", ReplyAction="http://zenchatservice.azurewebsites.net/ZenChat.svc/ZenChatService/RecieveChatMes" +
            "sageResponse")]
        System.Threading.Tasks.Task RecieveChatMessageAsync(int userId, int messageId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZenChatServiceChannel : ZenChat.ZenChatService.ZenChatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZenChatServiceClient : System.ServiceModel.ClientBase<ZenChat.ZenChatService.ZenChatService>, ZenChat.ZenChatService.ZenChatService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ZenChatServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ZenChatServiceClient.GetBindingForEndpoint(endpointConfiguration), ZenChatServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZenChatServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ZenChatServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZenChatServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ZenChatServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZenChatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<ZenChat.ZenChatService.User> ChangeUsernameAsync(int userId, string newUsername) {
            return base.Channel.ChangeUsernameAsync(userId, newUsername);
        }
        
        public System.Threading.Tasks.Task<ZenChat.ZenChatService.User> GetUserAsync(string phoneNumber) {
            return base.Channel.GetUserAsync(phoneNumber);
        }
        
        public System.Threading.Tasks.Task<ZenChat.ZenChatService.User> GetUserFromIdAsync(int id) {
            return base.Channel.GetUserFromIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<int, ZenChat.ZenChatService.User>> LoginAsync(string phone, string name) {
            return base.Channel.LoginAsync(phone, name);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ZenChat.ZenChatService.User>> GetFriendsAsync(int userId) {
            return base.Channel.GetFriendsAsync(userId);
        }
        
        public System.Threading.Tasks.Task AddFriendAsync(int userId, string otherPhone) {
            return base.Channel.AddFriendAsync(userId, otherPhone);
        }
        
        public System.Threading.Tasks.Task RemoveFriendAsync(int userId, string otherPhone) {
            return base.Channel.RemoveFriendAsync(userId, otherPhone);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ZenChat.ZenChatService.ChatRoom>> GetAllChatRoomsAsync(int userId) {
            return base.Channel.GetAllChatRoomsAsync(userId);
        }
        
        public System.Threading.Tasks.Task<ZenChat.ZenChatService.ChatRoom> GetChatRoomAsync(int chatRoomId, int playerId) {
            return base.Channel.GetChatRoomAsync(chatRoomId, playerId);
        }
        
        public System.Threading.Tasks.Task<ZenChat.ZenChatService.ChatRoom> CreateChatRoomAsync(int userId, string topic) {
            return base.Channel.CreateChatRoomAsync(userId, topic);
        }
        
        public System.Threading.Tasks.Task InviteToChatRoomAsync(int userId, string phoneNumber, int chatRoomId) {
            return base.Channel.InviteToChatRoomAsync(userId, phoneNumber, chatRoomId);
        }
        
        public System.Threading.Tasks.Task RemoveFromChatRoomAsync(int userId, string phoneNumber, int chatRoomId) {
            return base.Channel.RemoveFromChatRoomAsync(userId, phoneNumber, chatRoomId);
        }
        
        public System.Threading.Tasks.Task<ZenChat.ZenChatService.ChatRoom> WriteGroupChatMessageAsync(int userId, int chatRoomId, string message) {
            return base.Channel.WriteGroupChatMessageAsync(userId, chatRoomId, message);
        }
        
        public System.Threading.Tasks.Task<ZenChat.ZenChatService.PrivateConversation> GetPrivateConversationAsync(int userId, string otherPhone) {
            return base.Channel.GetPrivateConversationAsync(userId, otherPhone);
        }
        
        public System.Threading.Tasks.Task<ZenChat.ZenChatService.PrivateConversation> WritePrivateChatMessageAsync(int userId, string otherPhone, string message) {
            return base.Channel.WritePrivateChatMessageAsync(userId, otherPhone, message);
        }
        
        public System.Threading.Tasks.Task ReadChatMessageAsync(int userId, int messageId) {
            return base.Channel.ReadChatMessageAsync(userId, messageId);
        }
        
        public System.Threading.Tasks.Task RecieveChatMessageAsync(int userId, int messageId) {
            return base.Channel.RecieveChatMessageAsync(userId, messageId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ZenChatService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_ZenChatService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ZenChatService)) {
                return new System.ServiceModel.EndpointAddress("http://zenchatservice.azurewebsites.net/ZenChat.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_ZenChatService)) {
                return new System.ServiceModel.EndpointAddress("https://zenchatservice.azurewebsites.net/ZenChat.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_ZenChatService,
            
            BasicHttpsBinding_ZenChatService,
        }
    }
}
