Dokumentation
=============
Alain Keller, Pascal Honegger und Seraphin Rihm
Version 1.0, 15.03.2016
:toc:

== Framework

=== C#
Wir werden C#6 / .Net 4.6.1 verwenden. Das Projekt wird als sogenannte Windows Universal App erstellt und ist somit auch für Windows-Mobile ausgelegt.

== Datenstruktur

=== Aufbau des Projektordner
Die Dateien werden in verschiede Ordner (Namespaces) unterteilt. Diese werden nach Überthemen des Projektes geordnet. Die Ordner sind doppelt vorhanden, einmal im Haupt-Projekt und einmal im Test-Projekt.

== Continous Integration

link:https://ci.appveyor.com/project/PascalHonegger/spaceinvaders[AppVeyor]
unterstützt als einzige CI neben Travis C#, benötigt aber weniger Konfigurationen.

== VCS-Server
link:https://github.com/PascalHonegger/SpaceInvaders[Github]

== Pflichtenheft

=== Chatfunktionen

* User
** Registrieren
** Anmelden
** Kontakliste
*** Kann nur mit Leuten in seiner Kontakliste chaten.
** Status

* Userinterface
** Status der Nachricht wird angezeigt (Haken)
** Logische gliederung der Nachrichten (Rechts und Links)
** Man wird über neue Nachrichten informiert.

* Chat
** Nur Text
** History
** Gruppe


== Architektur


== Fazit
