Teamwork
========
Alain Keller, Pascal Honegger und Seraphin Rihm
Version 1.2, 28.04.2016
:toc:

= 05.04.2016
== Technische Probleme
Bis jetzt hatten wir nie grössere technische Schwierigkeiten. Im Normalfall konnten alle Treiber installiert und verwendet werden. Bei Seraphin war heute die Zeit gekommen, wo er ein Windows-Update ausführen musste. Visual Studio weigerte sich ohne dieses Update zu funktionieren und Seraphin hatte keine Wahl. Doch das Update stellte sich als eine riesige Zeitverschwendung heraus. Während 5 Stunden war der Laptop nicht ansprechbar und war komplett in das Update vertieft. In dieser Zeit konnte Seraphin nur sehr begrenzt arbeiten und musste sich darauf reduzieren uns zu unterstützen. Natürlich sind gewisse Updates unvermeidlich, trotzdem sollte man versuchen solche Blockaden im Voraus zu beseitigen, zum Beispiel zuhause während man gerade an etwas anderem Arbeitet.

== "Schwarze Magie"
Wir nennen unerklärliche Phänomene oft "Schwarze Magie". Diese "Schwarze Magie" ist besonders nervig, da man oft keine Ahnung hat, was sie verursacht. So hatten wir heute einen sehr verwirrenden Fall. Pascal hat sich hauptsächlich auf die Implementierung des Server fokussiert. Er hat dabei alle Kernfunktionen mit Tests überprüft und die vermeintlich funktionierende Version auf dem Server installiert. Das Problem: Auf dem Server ging nichts! Beim Aufruf eines Services warft der Server immer eine "FaultException: Index was out of Bounds of Array" und eine Zeile im Code, welche nicht einmal ein Array beinhaltete. Zu Testzwecken hat Pascal diese Zeile auskommentiert und den Code lokal installiert. Dort kann ohne Probleme mit dem sogenannten C#-Testclient alle Serviceoperationen aufrufen und die Antworten als XML sehen. Das Problem hierbei: Der auskommentierte Code warf immer noch einen komplett bezugslosen Fehler. Falls man versucht hat den einen Breakpoint zu setzen, um somit den Fehler genauer zu analysieren, sagte Visual Studio "Won't stop at Breakpoint because no Symbols are loaded" -> Der kompilierte / installierte Quellcode konnte nicht korrekt geladen werden. Im Internet findet man keine Ähnlichen Fälle von unerklärbaren Fehlern. Der Code funktioniert einwand frei, bis man diesen als Service installiert.
Die Lösung auf das Problem ergab sich dann erst durch einen Zufall: Beim ausführen einer Code-Analyse um allgemeine Fehler zu finden und beheben informiert der .Net-Compiler darüber, dass der Namespace "ZenChat" nicht existiert. Diese Warnung wurde bis zu diesem Zeitpunkt unterdrückt, obwohl dies eigentlich als Fehler behandelt werden sollte. Vor einer geraumen Zeit wurde entschieden, dass das Projekt "ZenChat" in "ZenChatService" umbenannt werden sollte. Dies wurde aufgrund der Namenskonvention im Client entschieden. Jedoch wurde eine kleinere Anpassung in einer Konfigurations-Datei nicht gemacht und hat die komplette Installation gestört. Dieser Fehler wäre vielleicht nicht aufgetreten, hätten wir das Refactoring als Team durchgeführt oder ein Code-Review durchgeführt!

= Tipps
== Selbe wie zuvor
Bereits notwendige Tipps sind unter link:https://github.com/PascalHonegger/SpaceInvaders/blob/master/Dokumentation/_Source/Teamwork.adoc[unserem alten Projekt] (unten) zu finden. Diese Tipps sind immer noch gültig und sollten auf jeden Fall angewandt werden.

== Clean Code
Code sollte möglichst leserlich sein. Daher Code soweit möglich den link:http://clean-code-developer.de/[Clean Code Developer]-Richtlinien entsprechen. Dies Sprachen unabhängige Standards helfen sowohl bei der Entwicklung / Erweiterbarkeit als auch bei der Leserlichkeit für die Bewertung.

== Pair-Programming / Code-Review
Es ist wichtig dafür zu sorgen, dass ein Code mindestens von zwei personen begutachtet wird. Entweder entwickelt man den Code zusammen (Pair-Programming) und unterstützt sich gegenseitig. Die andere Variante ist vergleichbar mit dem normalen Implementieren. Man entwickelt den Code alleine und präsentiert am Schluss seinen Code einem anderen Entwickler. Dieser versucht unseren Code zu verstehen und versucht die Logik zu hinterfragen. Oft fallen dabei noch kleinigkeiten auf, welche einem beim alleinigen Entwickeln nicht aufgefallen sind. Dieses Code-Review gehört normalerweise zu den DODs (siehe unten)

== Definition of Done (DOD)
Beim Arbeiten nach Scrum sollte man sogenannte DODs definieren. Diese "Checkliste" muss immer erfüllt sein, wenn man eine Story / ein Feature abschliessen möchte. Im Normalfall beinhalten die DODs mindestens:
* Neuer Code ist ausreichend kommentiert
* Code wurde im Pair-Programming entwickelt oder durch einCode-Review überprüft
* Code ist gut getestet
* Code entspricht den Code-Konventionen (Naming, File-Header, Location...)
* Code ist im Git-Repository vorhanden
* Keine Fehler treten auf, Feature abgeschlossen